export const FETCH_WEATHER_ERROR = "FETCH_WEATHER_ERROR";
export const SEARCHED_LOCATION = "SEARCHED_LOCATION";
export const UNITS_CHANGED = "UNITS_CHANGED";
export const WEATHER_DATA_UPDATED = "WEATHER_DATA_UPDATED";
